// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpaicoqbwyrsgznuhzfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYWljb3Fid3lyc2d6bnVoemZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTUyNDIsImV4cCI6MjA2NDU5MTI0Mn0.R2tZihtRJ3Cs-vsrKm8J6fqhFYnNpinzs4wv6cZ_w04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);